### ISSUE TITLE
Redis Datasource yaml to import sentinel connexion

### ISSUE THREAD

**Issue by buramundo** [RedisGrafana/grafana-redis-datasource#165]
## Summary
need field to have a sentinel connexion via redis.yaml

## Relevant information
I make GIT OPS K8S RANCHER for import Datasource i need the correct syntax to import a sentinel datasource of redis : 
How i specify type: sentinel (as UI) and master name ? 

datasources:
  - name: Redis
    type: redis-datasource
    access: proxy
    orgId: 1
    isDefault: true
    version: 1
    url: redis://host.docker.internal:6379
    jsonData:
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    editable: true

**Comment by mikhailredis** [comment]
Hello @buramundo. Great questions, I have to add it to the documentation.
Please let me know if it works:
```
datasources:
  - name: Sentinel
    type: redis-datasource
    access: proxy
    orgId: 1
    isDefault: true
    version: 1
    url: redis://host.docker.internal:6379
    jsonData:
      client: sentinel
      sentinelName: Test
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    editable: true
```
