### ISSUE TITLE
Can not see Redis data in Grafana

### ISSUE THREAD

**Issue by boriskogan81** [RedisGrafana/grafana-redis-datasource#190]
## Summary

Grafana says it's connected to Redis, but I can't get any data.

## Relevant information

I am running Grafana and Redis on a docker image from here:  https://github.com/collabnix/redisedge-grafana

Redis is running and has the data I'm looking for in a time series:
![image](https://user-images.githubusercontent.com/10279403/116266720-6a8bca80-a784-11eb-9d85-9bf4735429fd.png)

Grafana is running and successfully connecting to Redis as a data source:

![image](https://user-images.githubusercontent.com/10279403/116267324-fbfb3c80-a784-11eb-8802-f1cf2d6781df.png)

But I'm only intermittently successful in seeing the data in the dashboard. The query sometimes runs and sometimes doesn't:

![image](https://user-images.githubusercontent.com/10279403/116284430-be52df80-a795-11eb-9d80-fecb0f6c4bc9.png)

**Comment by mikhailredis** [comment]
@boriskogan81 Do you use docker-compose file from the https://github.com/collabnix/redisedge-grafana?

It's based on the image `ajeetraina/grafana-redisedge` which was built 6 months ago.
```
grafana:
    image: ajeetraina/grafana-redisedge
    environment:
      - GF_INSTALL_PLUGINS=redis-app
  #  depends_on:
  #    - prometheus
    ports:
      - 3000:3000
```

We fixed a couple of connectivity issues since then and fixed race condition in the Grafana.

I would recommend to try `grafana/grafana:latest` or our nightly build with Redis-app pre-installed:
```
docker run -p 3000:3000 --name=redis-app ghcr.io/redisgrafana/redis-app:latest
```

Please let me know if it works for you.
