### ISSUE TITLE
automate redis plugin installation 

### ISSUE THREAD

**Issue by zencircle** [RedisGrafana/grafana-redis-datasource#250]
## Summary
I am working on automating the plugin installation and unable to  apply additional parameters in datasource.yaml file . Values listed [here](https://github.com/RedisGrafana/grafana-redis-datasource/blob/master/provisioning/datasources/redis.yaml) seems to work.
## Relevant information

```yaml 
 datasource.yaml: |-
    apiVersion: 1
    - name: Redis
      type: redis-datasource
      url: redis://redis-master.default.svc.cluster.local:6379
      Client: standalone
      jsonData:
        tlsCACert: "-----BEGIN CERTIFICATE-----"
        tlsClientCert: "-----BEGIN CERTIFICATE-----"
        tlsClientKey: "-----BEGIN RSA PRIVATE KEY-----"
        Password: "PasswordXXX"
        TLSAuth:        true
        TLSSkipVerify:  true
      editable: true
```

**Comment by zencircle** [comment]
Found additional documentation [here](https://redisgrafana.github.io/redis-datasource/provisioning/). Below config worked for me 
```
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Redis
      type: redis-datasource
      url: redis://hmda-redis-master.default.svc.cluster.local:6379
      editable: true
      jsonData:
        client: standalone
        tlsAuth: true
        tlsSkipVerify: true
      secureJsonData:
        password: "PasswordXXX"      
        tlsCACert: "-----BEGIN CERTIFICATE-----"
        tlsClientCert: "-----BEGIN CERTIFICATE-----"
        tlsClientKey: "-----BEGIN RSA PRIVATE KEY-----"
```
