### ISSUE TITLE
How to set the redis password field when adding the datasource via the Grafana API?

### ISSUE THREAD

**Issue by vgoklani** [RedisGrafana/grafana-redis-datasource#273]
Hey there,

I'm trying to create a new datasource via the Grafana API for redis.  When calling the API, the plugin gets created, but the password field is blank, and therefore the plugin can't connect to our redis instance. I'm able to fix this manually by logging in to the Grafana web app, and manually pasting in the password.... which is incredibly annoying :)

Here's how I'm creating the `schema` for redis. I've also included the `schema` for InfluxDB, which works correctly (i.e. the password is getting set when passed via the API)

    influxdb_schema = {
        "name": "InfluxDB",
        "type": "influxdb",
        "typeName": "InfluxDB",
        "url": f'http://{os.environ["influxdb_host"]}:{os.environ["influxdb_port"]}',
        "access": "proxy",
        "database": "udp",
        "isDefault": True,
        "user": os.environ["influxdb_username"],
        "password": os.environ["influxdb_password"],
    }

    redis_schema = {
        "name": "Redis",
        "type": "redis-datasource",
        "typeName": "Redis",
        "url": f'redis://{os.environ["redis_host"]}:{os.environ["redis_port"]}',
        "access": "proxy",
        "database": "",
        "isDefault": False,
        "user": "",
        "password": os.environ["redis_password"],
    }

I then just make the REST call:

    response = self._session.post(url=f"https://{self._root_url}/grafana/api/datasources", data=json.dumps(schema),)
 
The password gets set for InfluxDB, but not for redis. Should I be using a different parameter for the redis_schema, is `password` not the correct parameter? And yes, the environment variables are all defined.

Thanks!

**Comment by mikhail-vl** [comment]
@vgoklani Redis's password is a part of the `secureJsonData` and should be set accordingly in the API request.

```
apiVersion: 1

datasources:
  - name: Redis
    type: redis-datasource
    access: proxy
    orgId: 1
    isDefault: true
    version: 1
    url: redis://host.docker.internal:6379
    jsonData:
      client: standalone
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    editable: true
    secureJsonData:
      password: $PASSWORD
```
