### ISSUE TITLE
Provided dashboards broken in Grafana v10

### ISSUE THREAD

**Issue by GDWR** [RedisGrafana/grafana-redis-datasource#312]
## Summary
When attempting to use this plugin with Grafana v10 the provided Streaming dashboard is unable to render graphs, previous versions (8 and 9) seem to have no problem with doing so.

## Relevant information
I am using this docker compose setup for testing
```yaml
services:
  redis:
    image: redis/redis-stack-server

  grafana:
    image: grafana/grafana:10.0.9
    environment:
      GF_INSTALL_PLUGINS: redis-datasource
    ports:
      - "3000:3000"
```

Once started I add the datasource
![image](https://github.com/RedisGrafana/grafana-redis-datasource/assets/57012020/195f5c22-1b96-47ef-8223-18940d646b82)

Then import the default/provided dashboards
![image](https://github.com/RedisGrafana/grafana-redis-datasource/assets/57012020/7cf180ae-0aa8-4984-b889-d5d01c4d7eb0)

And then check the streaming dashboard, to see empty graphs. But can view data
![image](https://github.com/RedisGrafana/grafana-redis-datasource/assets/57012020/15eaa06c-7fc0-4a20-9e88-7474a9398792)

This same process works (dashboard renders graphs) on v8 and v9, tested using grafana docker version `:8.` and `:9.5.14`. So seems like an issues specifically with v10.

---

For now I will be pinning to grafana v9, would love to hear back if this is resolved so I can use the latest grafana version. 

Cheers,
GDWR
