### ISSUE TITLE
Special configured  on the Redis databases doesn't work in  Sentinel mode

### ISSUE THREAD

**Issue by hyh555** [RedisGrafana/grafana-redis-datasource#62]
I use /db-number or ?db=db-number in the Data Source URL to specify the database number as defined in the Schema.
but It doesn't work in Sentinel mode。

**Comment by mikhailredis** [comment]
@hyh555 Thank you for opening the issue.

Could you please provide the screenshot with your data source configuration and clarify what is not working to investigate.

**Comment by mikhailredis** [comment]
@hyh555 We did not hear back from you regarding this issue.
Please provide more details if you still require assistance.

**Comment by EraYaN** [comment]
This is still an issue, it seems like it tries to send the SELECT command to the sentinel

So you get tons of these:
```
lvl=eror msg="Query data error" error="failed to query data: Failed to query data: rpc error: code = Unknown desc = ERR unknown command `SELECT`, with args beginning with: `1`, "
```

With the config (as an example)

```yaml
    - orgId: 1
      version: 2
      name: Redis
      type: redis-datasource
      access: proxy
      url: redis://redis.default.svc.cluster.local:26379?db=1
      jsonData:
        acl: false
        client: sentinel
        sentinelName: main
      secureJsonData:
        password: $REDIS_PASSWORD
        sentinelPassword: $REDIS_PASSWORD
```
